<a href="https://colab.research.google.com/github/Bayzid03/PyTorch-Playground/blob/main/Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pip install torch torchvision torchaudio

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import torch
print("PyTorch Version:",torch.__version__)
print("CUDA available:",torch.cuda.is_available())

PyTorch Version: 2.5.1+cpu
CUDA available: False


In [ ]:
import torch

# Scalar (0D tensor)
scalar = torch.tensor(5)
print("Scalar:", scalar)
print("Shape:", scalar.shape)

# Vector (1D tensor)
vector = torch.tensor([1, 2, 3])
print("\nVector:", vector)
print("Shape:", vector.shape)

# Matrix (2D tensor)
matrix = torch.tensor([[1, 2], [3, 4]])
print("\nMatrix:\n", matrix)
print("Shape:", matrix.shape)

# 3D Tensor
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Tensor:\n", tensor3d)
print("Shape:", tensor3d.shape)

random_tensor = torch.rand(2, 3)
print("Random Tensor:", random_tensor)
print("Shape:", random_tensor.shape)
print("DataType:", random_tensor.dtype)
print("Device:", random_tensor.device)


Scalar: tensor(5)
Shape: torch.Size([])

Vector: tensor([1, 2, 3])
Shape: torch.Size([3])

Matrix:
 tensor([[1, 2],
        [3, 4]])
Shape: torch.Size([2, 2])

3D Tensor:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])
Random Tensor: tensor([[0.2593, 0.1206, 0.8649],
        [0.6671, 0.5468, 0.8844]])
Shape: torch.Size([2, 3])
DataType: torch.float32
Device: cpu


In [ ]:
# Addition and Multiplication
a= torch.tensor([1,2])
b= torch.tensor([3,4])

print("Addition:", a+b)
print("Multiplication:", a*b)

Addition: tensor([4, 6])
Multiplication: tensor([3, 8])


Matrix Multiplication

In [ ]:
matrix1 = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[5, 6], [7, 8]])

result = torch.matmul(matrix1, matrix2)
print("Matrix Multiplication:\n", result)

Matrix Multiplication:
 tensor([[19, 22],
        [43, 50]])


Reshaping Tensors

In [ ]:
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
reshaped = tensor.view(2, 3)  # Reshape to 2 rows and 3 columns
print("Reshaped Tensor:\n", reshaped)

Reshaped Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])


Tasks: 1. Creating a 2D tensor of size (3,4) with random values.
       2. Perform element wise addition with another tensor of the same size.
       3. Reshape the resulting tensor to a 2*6 shape.

In [ ]:
tensor1 = torch.rand(3, 4)
print("Tensor 1 (3*4): \n",tensor1)

tensor2 = torch.rand(3, 4)
print("Tensor 2 (3*4): \n", tensor2)

result = tensor1 + tensor2
print("Element-Wise addition (3*4):\n", result)

reshaped_result = result.view(2, 6)
print("Reshaped Result (2*6): \n", reshaped_result)

Tensor 1 (3*4): 
 tensor([[0.4539, 0.6674, 0.3819, 0.2527],
        [0.4538, 0.7138, 0.2178, 0.4452],
        [0.4388, 0.8855, 0.1904, 0.4635]])
Tensor 2 (3*4): 
 tensor([[0.5501, 0.5398, 0.2583, 0.2230],
        [0.2039, 0.4301, 0.4047, 0.8707],
        [0.5994, 0.4152, 0.4990, 0.8445]])
Element-Wise addition (3*4):
 tensor([[1.0040, 1.2072, 0.6402, 0.4756],
        [0.6577, 1.1439, 0.6224, 1.3159],
        [1.0381, 1.3007, 0.6894, 1.3080]])
Reshaped Result (2*6): 
 tensor([[1.0040, 1.2072, 0.6402, 0.4756, 0.6577, 1.1439],
        [0.6224, 1.3159, 1.0381, 1.3007, 0.6894, 1.3080]])


Automatic Differentiation with AutoGrad
* When training a neural network, we adjust the model's weights (w) to minimize errors. This process is called BackPropogation. It uses gradients to do that. Gradient show how much each weight should change to reduce the error (loss)
* torch.autograd helps to compute gradients automatically.

In [ ]:
import torch

# Create a tensor with requires_grad=True
x = torch.tensor(3.0, requires_grad=True)

# Perform some operations
y = x ** 2  # y = x^2
z = 2 * y + 3  # z = 2y + 3

# Compute gradients
z.backward()  # Backpropagate

# Gradient of z with respect to x (dz/dx)
print("Gradient (dz/dx):", x.grad)


Gradient (dz/dx): tensor(12.)


In [ ]:
with torch.no_grad():
    x = torch.tensor(3.0, requires_grad=True)
    y = x ** 2
    print("Gradient computation disabled:", y.requires_grad)


Gradient computation disabled: False


In [ ]:
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2
y.backward()

# Check the gradient
print("Before zeroing:", x.grad)

# Zero the gradient
x.grad.zero_()
print("After zeroing:", x.grad)


Before zeroing: tensor(6.)
After zeroing: tensor(0.)


Computing Gradients for multiple variables

In [ ]:
a = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, 3, requires_grad=True)

# Element-wise operations
c = a * b
d = c.sum()  # Scalar output

# Backpropagation
d.backward()

# Gradients
print("Gradient of a:\n", a.grad)
print("Gradient of b:\n", b.grad)


Gradient of a:
 tensor([[-1.4726,  2.2852,  1.1395],
        [-1.8295, -0.1403, -0.4088]])
Gradient of b:
 tensor([[-0.9477, -0.5214,  1.2121],
        [-0.0907,  0.5103,  0.1629]])
